export const actions = {
  GET_DOORS_START: 'GET_DOORS_START',
  GET_DOORS_SUCCESS: 'GET_DOORS_SUCCESS',
  GET_DOORS_FAILED: 'GET_DOORS_FAILED',
  SELECT_DOOR: 'SELECT_DOOR',
  ACCESS_DOOR_START: 'ACCESS_DOOR_START',
  ACCESS_DOOR_SUCCESS: 'ACCESS_DOOR_SUCCESS',
  ACCESS_DOOR_FAILED: 'ACCESS_DOOR_FAILED',
  ACCESS_DOOR: 'ACCESS_DOOR',
};
